### ISSUE TITLE
Current account

### ISSUE THREAD

**Issue by peter-bread** [peter-bread/git-ssh-management#10]
See if I can read the current account from one of the gh config files rather than making api calls

**Comment by ak22112** [comment]
if i install `yq`, i can do:

```bash
yq -r '.["github.com"].user' ~/.config/gh/hosts.yml
```

This is much faster than having to make an API call on every cd.

Since this will be embedded in the go binary, users will not need to install yq themselves -- only I, the developer, need to have it installed at compile time.

**Comment by peter-bread** [comment]
Just need to implement this

**Comment by peter-bread** [comment]
done
